dist: trusty
language: java
jdk:
  - oraclejdk8

install: ant

addons:
    packages:
      - ant
      - ant-optional
      - oracle-java8-installer

script:
  - ant integracion-continua 

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
    
