language: java
jdk:
  - openjdk8
  - oraclejdk8

install: ant

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ant
      - ant-optional
      - oracle-java8-installer

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - juanpablofresia@gmail.com
      - veronicaleguizamon90@gmail.com
      - sherfiuba@gmail.com
    on_failure: always
