language: java
jdk:
    - oraclejdk8
addons:
    apt:
        packages:
            - oracle-java8-installer
notifications:
  email:
    recipients:
      - juanpablofresia@gmail.com
      - veronicaleguizamon90@gmail.com
      - sherfiuba@gmail.com
    on_failure: always
    
